# Generated by Django 5.0.4 on 2024-04-30 06:46

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('user_address_line_1', models.CharField(blank=True, max_length=254, null=True)),
                ('user_address_line_2', models.CharField(blank=True, max_length=254, null=True)),
                ('user_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
